apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sync-registry-cronjob.fullname" . }}-config
  labels:
    app: {{ include "sync-registry-cronjob.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  registry.yaml: |
    registries:
{{- range .Values.config.registries }}
      - source_registry: {{ .source_registry | quote }}
        source_repository: {{ .source_repository | quote }}
        dest_registry: {{ .dest_registry | quote }}
        dest_repository: {{ .dest_repository | quote }}
        tag_limit: {{ .tag_limit }}
        insecure_tls: {{ default false .insecure_tls }}
{{- if .exclude_patterns }}
        exclude_patterns:
{{- range .exclude_patterns }}
          - {{ . | quote }}
{{- end }}
{{- end }}
{{- if .version_filters }}
        version_filters:
{{- range .version_filters }}
          - major: {{ .major }}
            minor: {{ .minor }}
            get_latest: {{ default false .get_latest }}
{{- end }}
{{- end }}
{{- end }}
