apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "sync-registry-cronjob.fullname" . }}
  labels:
    app: {{ include "sync-registry-cronjob.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  schedule: {{ .Values.cronjob.schedule | quote }}
  successfulJobsHistoryLimit: {{ .Values.cronjob.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.cronjob.failedJobsHistoryLimit }}
  concurrencyPolicy: {{ .Values.cronjob.concurrencyPolicy }}
  jobTemplate:
    spec:
      backoffLimit: {{ .Values.cronjob.backoffLimit | default 2 }}
      template:
        metadata:
          labels:
            app: {{ include "sync-registry-cronjob.name" . }}
            app.kubernetes.io/instance: {{ .Release.Name }}
        spec:
          restartPolicy: OnFailure
          securityContext:
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
          containers:
          - name: sync-app
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
            env:
              - name: REGISTRY_CONFIG_PATH
                value: {{ .Values.env.REGISTRY_CONFIG_PATH | quote }}
              - name: SECRETS_CONFIG_PATH
                value: {{ .Values.env.SECRETS_CONFIG_PATH | quote }}
              - name: SYNC_CONCURRENCY
                value: {{ .Values.env.SYNC_CONCURRENCY | default "3" | quote }}
            volumeMounts:
              - name: config-volume
                mountPath: /config
                readOnly: true
              - name: secret-volume
                mountPath: /secret
                readOnly: true
              - name: gcr-volume
                mountPath: /gcr
                readOnly: true
              - name: tmp
                mountPath: /tmp
            resources:
              requests:
                cpu: {{ .Values.resources.requests.cpu }}
                memory: {{ .Values.resources.requests.memory }}
              limits:
                cpu: {{ .Values.resources.limits.cpu }}
                memory: {{ .Values.resources.limits.memory }}
          volumes:
          - name: secret-volume
            secret:
              secretName: {{ include "sync-registry-cronjob.fullname" . }}-secret
          - name: config-volume
            configMap:
              name: {{ include "sync-registry-cronjob.fullname" . }}-config
          - name: gcr-volume
            secret:
              secretName: {{ include "sync-registry-cronjob.fullname" . }}-gcr
          - name: tmp
            emptyDir: {}
