apiVersion: v1
kind: Secret
metadata:
  name: registries-secret
  labels:
    app: {{ .Release.Name }}
type: Opaque
stringData:
  secrets.yaml: |
    secrets:
{{- range .Values.secrets }}
  {{- if .source_registry }}
      - source_registry: "{{ .source_registry }}"
        source_type: "{{ .source_type }}"
        username: "{{ .username }}"
        password: "{{ .password }}"
  {{- end }}
      - dest_registry: "{{ .dest_registry }}"
        {{- if .service_account_key }}
        service_account_key: "{{ .service_account_key }}"
        {{- else }}
        username: "{{ .username }}"
        password: "{{ .password }}"
        {{- end }}
        type: "{{ .type }}"
{{- end }}
