apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sync-registry-cronjob.fullname" . }}-secret
  labels:
    app: {{ include "sync-registry-cronjob.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  secrets.yaml: |
    secrets:
{{- range .Values.secrets }}
  {{- if .source_registry }}
      - source_registry: {{ .source_registry | quote }}
        source_type: {{ .source_type | quote }}
        username: {{ .username | quote }}
        password: {{ .password | quote }}
        insecure_tls: {{ default false .insecure_tls }}
  {{- else if .dest_registry }}
      - dest_registry: {{ .dest_registry | quote }}
        type: {{ .type | quote }}
        insecure_tls: {{ default false .insecure_tls }}
        {{- if .service_account_key }}
        service_account_key: {{ .service_account_key | quote }}
        {{- else }}
        username: {{ .username | quote }}
        password: {{ .password | quote }}
        {{- end }}
  {{- end }}
{{- end }}
