apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sync-registry-cronjob.fullname" . }}-gcr
  labels:
    app: {{ include "sync-registry-cronjob.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
data:
  gcr.json: {{ .Values.gcr.secrets | quote }}
