image:
  repository: europe-west3-docker.pkg.dev/$gcp_project/image-mirror/syncer
  tag: v1.0.0
  pullPolicy: IfNotPresent

cronjob:
  schedule: "0 0 * * *"  # Every day at midnight
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  concurrencyPolicy: "Forbid"
  backoffLimit: 2

env:
  REGISTRY_CONFIG_PATH: "/config/registry.yaml"
  SECRETS_CONFIG_PATH: "/secret/secrets.yaml"
  SYNC_CONCURRENCY: "3"

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

gcr:
  secrets: ""

config:
  registries:
    - source_registry: "quay.io"
      source_repository: "argoproj/argocd"
      dest_registry: "europe-west3-docker.pkg.dev"
      dest_repository: "$gcp_project/argocd/argocd"
      tag_limit: 3
      insecure_tls: false
      exclude_patterns:
        - "alpine"
        - "distroless"
        - "sha"
        - "poc"
        - "release"
        - "latest"
        - "master"
        - "rc"
      version_filters:
        - major: 2
          minor: 12
          get_latest: false
        - major: 2
          minor: 11
          get_latest: false
    - source_registry: "ghcr.io"
      source_repository: "dexidp/dex"
      dest_registry: "europe-west3-docker.pkg.dev"
      dest_repository: "$gcp_project/argocd/dex"
      tag_limit: 3
      exclude_patterns:
        - "alpine"
        - "distroless"
        - "sha"
        - "poc"
        - "release"
        - "latest"
        - "master"
        - "rc"
      version_filters:
        - major: 2
          minor: 41
          get_latest: true
    - source_registry: "registry.k8s.io"
      source_repository: "kube-state-metrics/kube-state-metrics"
      dest_registry: "europe-west3-docker.pkg.dev"
      dest_repository: "$gcp_project/kube-state-metrics/kube-state-metrics"
      tag_limit: 3
      exclude_patterns:
        - "rc"
        - "alpha"
        - "beta"
        - "sha"
      version_filters:
        - major: 2
          minor: 13
          get_latest: false
    - source_registry: "registry.k8s.io"
      source_repository: "autoscaling/cluster-autoscaler"
      dest_registry: "europe-west3-docker.pkg.dev"
      dest_repository: "$gcp_project/autoscaling/cluster-autoscaler"
      tag_limit: 5
      exclude_patterns:
        - "rc"
        - "alpha"
        - "beta"
        - "sha"
      version_filters:
        - major: 1
          minor: 30
          get_latest: false

secrets:
  - dest_registry: "europe-west3-docker.pkg.dev"
    type: "gcr"
    service_account_key: "/gcr/gcr.json"
  - source_registry: "docker.io"
    source_type: "dockerhub"
    username: "example"
    password: "example"
